# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-27 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('is_login', models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=0, verbose_name='登录状态')),
            ],
        ),
    ]
